In [26]:
import os
import psycopg2 as pg2

In [27]:
os.chdir('/home/jovyan')

In [28]:
def connect_to_postgres():
    """Preconfigured to create a connection to postgres database.

    Returns
    -------
    con, cur : connect_to_postgres()
    """

    con = pg2.connect(host='this_postgres', user='postgres', database='postgres')

    return con, con.cursor()

In [29]:
con, cur = connect_to_postgres()

In [30]:
cur.execute('SELECT COUNT(*) FROM adult')

In [31]:
print(cur.fetchall())

[(32561,)]

In [32]:
cur.execute('SELECT * FROM adult LIMIT 5')

In [33]:
print(cur.fetchall())

[(39, ' State-gov', 77516, ' Bachelors', 13, ' Never-married', ' Adm-clerical', ' Not-in-family', ' White', ' Male', 2174, 0, 40, ' United-States', ' <=50K'), (50, ' Self-emp-not-inc', 83311, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 13, ' United-States', ' <=50K'), (38, ' Private', 215646, ' HS-grad', 9, ' Divorced', ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K'), (53, ' Private', 234721, ' 11th', 7, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' Black', ' Male', 0, 0, 40, ' United-States', ' <=50K'), (28, ' Private', 338409, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' Black', ' Female', 0, 0, 40, ' Cuba', ' <=50K')]

In [34]:
cur.execute("SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE table_name = 'adult';")

In [35]:
cur.fetchall()

[('age',),
 ('workclass',),
 ('fnlwgt',),
 ('education',),
 ('education_num',),
 ('marital_status',),
 ('occupation',),
 ('relationship',),
 ('race',),
 ('gender',),
 ('capital_gain',),
 ('capital_loss',),
 ('hours_per_week',),
 ('native_country',),
 ('income_label',)]

In [21]:
cur.execute('SELECT * FROM adult LIMIT 5')

In [23]:
con.close()

In [38]:
cur.execute("SELECT * FROM information_schema.COLUMNS;")

In [39]:
cur.fetchall()

[('postgres',
  'pg_catalog',
  'pg_proc',
  'proname',
  1,
  None,
  'NO',
  'name',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'name',
  None,
  None,
  None,
  None,
  '1',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'pronamespace',
  2,
  None,
  'NO',
  'oid',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'oid',
  None,
  None,
  None,
  None,
  '2',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'proowner',
  3,
  None,
  'NO',
  'oid',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'oid',
  None,
  None,
  None,
  None,
  '3',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'prolang',
  4,
  None,
  'NO',
  'oid',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'oid',
  None,
  None,
  None,
  None,
  '4',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'procost',
  5,
  None,
  'NO',
  'real',
  None,
  None,
  24,
  2,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'float4',
  None,
  None,
  None,
  None,
  '5',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'prorows',
  6,
  None,
  'NO',
  'real',
  None,
  None,
  24,
  2,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'float4',
  None,
  None,
  None,
  None,
  '6',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'provariadic',
  7,
  None,
  'NO',
  'oid',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'oid',
  None,
  None,
  None,
  None,
  '7',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'protransform',
  8,
  None,
  'NO',
  'regproc',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'regproc',
  None,
  None,
  None,
  None,
  '8',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'prokind',
  9,
  None,
  'NO',
  '"char"',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'char',
  None,
  None,
  None,
  None,
  '9',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'prosecdef',
  10,
  None,
  'NO',
  'boolean',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'bool',
  None,
  None,
  None,
  None,
  '10',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'proleakproof',
  11,
  None,
  'NO',
  'boolean',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'bool',
  None,
  None,
  None,
  None,
  '11',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'proisstrict',
  12,
  None,
  'NO',
  'boolean',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'bool',
  None,
  None,
  None,
  None,
  '12',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'proretset',
  13,
  None,
  'NO',
  'boolean',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'bool',
  None,
  None,
  None,
  None,
  '13',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'provolatile',
  14,
  None,
  'NO',
  '"char"',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'char',
  None,
  None,
  None,
  None,
  '14',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'proparallel',
  15,
  None,
  'NO',
  '"char"',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'char',
  None,
  None,
  None,
  None,
  '15',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'pronargs',
  16,
  None,
  'NO',
  'smallint',
  None,
  None,
  16,
  2,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'int2',
  None,
  None,
  None,
  None,
  '16',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'pronargdefaults',
  17,
  None,
  'NO',
  'smallint',
  None,
  None,
  16,
  2,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'int2',
  None,
  None,
  None,
  None,
  '17',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'prorettype',
  18,
  None,
  'NO',
  'oid',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'oid',
  None,
  None,
  None,
  None,
  '18',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'proargtypes',
  19,
  None,
  'NO',
  'ARRAY',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'oidvector',
  None,
  None,
  None,
  None,
  '19',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'proallargtypes',
  20,
  None,
  'YES',
  'ARRAY',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  '_oid',
  None,
  None,
  None,
  None,
  '20',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'proargmodes',
  21,
  None,
  'YES',
  'ARRAY',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  '_char',
  None,
  None,
  None,
  None,
  '21',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'proargnames',
  22,
  None,
  'YES',
  'ARRAY',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  '_text',
  None,
  None,
  None,
  None,
  '22',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'proargdefaults',
  23,
  None,
  'YES',
  'pg_node_tree',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'pg_node_tree',
  None,
  None,
  None,
  None,
  '23',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'protrftypes',
  24,
  None,
  'YES',
  'ARRAY',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  '_oid',
  None,
  None,
  None,
  None,
  '24',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'prosrc',
  25,
  None,
  'NO',
  'text',
  None,
  1073741824,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'text',
  None,
  None,
  None,
  None,
  '25',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'probin',
  26,
  None,
  'YES',
  'text',
  None,
  1073741824,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'text',
  None,
  None,
  None,
  None,
  '26',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'proconfig',
  27,
  None,
  'YES',
  'ARRAY',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  '_text',
  None,
  None,
  None,
  None,
  '27',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_proc',
  'proacl',
  28,
  None,
  'YES',
  'ARRAY',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  '_aclitem',
  None,
  None,
  None,
  None,
  '28',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typname',
  1,
  None,
  'NO',
  'name',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'name',
  None,
  None,
  None,
  None,
  '1',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typnamespace',
  2,
  None,
  'NO',
  'oid',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'oid',
  None,
  None,
  None,
  None,
  '2',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typowner',
  3,
  None,
  'NO',
  'oid',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'oid',
  None,
  None,
  None,
  None,
  '3',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typlen',
  4,
  None,
  'NO',
  'smallint',
  None,
  None,
  16,
  2,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'int2',
  None,
  None,
  None,
  None,
  '4',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typbyval',
  5,
  None,
  'NO',
  'boolean',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'bool',
  None,
  None,
  None,
  None,
  '5',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typtype',
  6,
  None,
  'NO',
  '"char"',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'char',
  None,
  None,
  None,
  None,
  '6',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typcategory',
  7,
  None,
  'NO',
  '"char"',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'char',
  None,
  None,
  None,
  None,
  '7',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typispreferred',
  8,
  None,
  'NO',
  'boolean',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'bool',
  None,
  None,
  None,
  None,
  '8',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typisdefined',
  9,
  None,
  'NO',
  'boolean',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'bool',
  None,
  None,
  None,
  None,
  '9',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typdelim',
  10,
  None,
  'NO',
  '"char"',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'char',
  None,
  None,
  None,
  None,
  '10',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typrelid',
  11,
  None,
  'NO',
  'oid',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'oid',
  None,
  None,
  None,
  None,
  '11',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typelem',
  12,
  None,
  'NO',
  'oid',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'oid',
  None,
  None,
  None,
  None,
  '12',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typarray',
  13,
  None,
  'NO',
  'oid',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'oid',
  None,
  None,
  None,
  None,
  '13',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typinput',
  14,
  None,
  'NO',
  'regproc',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'regproc',
  None,
  None,
  None,
  None,
  '14',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typoutput',
  15,
  None,
  'NO',
  'regproc',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'regproc',
  None,
  None,
  None,
  None,
  '15',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typreceive',
  16,
  None,
  'NO',
  'regproc',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'regproc',
  None,
  None,
  None,
  None,
  '16',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typsend',
  17,
  None,
  'NO',
  'regproc',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'regproc',
  None,
  None,
  None,
  None,
  '17',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typmodin',
  18,
  None,
  'NO',
  'regproc',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'regproc',
  None,
  None,
  None,
  None,
  '18',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typmodout',
  19,
  None,
  'NO',
  'regproc',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'regproc',
  None,
  None,
  None,
  None,
  '19',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typanalyze',
  20,
  None,
  'NO',
  'regproc',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'regproc',
  None,
  None,
  None,
  None,
  '20',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typalign',
  21,
  None,
  'NO',
  '"char"',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'char',
  None,
  None,
  None,
  None,
  '21',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('postgres',
  'pg_catalog',
  'pg_type',
  'typstorage',
  22,
  None,
  'NO',
  '"char"',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'postgres',
  'pg_catalog',
  'char',
  None,
  None,
  None,
  None,
  '22',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,